This folder collects the data given the csv.

In [16]:
import requests as rq
from bs4 import BeautifulSoup as bs
import pandas as pd 
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np


df = pd.DataFrame(columns=["SpeciesName", "NumReferences", "NumWords", "Error"])


#methods
#total number of words in page     
def total_Words(soup):
    totalWords = 0
    paragraph = soup.find_all("p")
    for i in range(len(paragraph)):
        totalWords = totalWords + len(paragraph[i].get_text())
   # print("Total number of words: " + str(totalWords))
    return totalWords
    
#total number of references 
def total_Ref(soup): 
    references_section = soup.find('ol', class_= 'references')

    if references_section:
        references = references_section.find_all('li')
        num_references = len(references)
       # print(f"Number of references: {num_references}")
        return num_references
    else:
        #print("No references found.")    
        return 0
    
#end of methods

In [17]:
birdSpecies = pd.read_csv("../data/speciesList.csv")

testSubset = birdSpecies.iloc[200:250, 1]

print(testSubset)

200       Melierax poliopterus
201           Micronisus gabar
202           Milvus aegyptius
203             Milvus migrans
204              Milvus milvus
205      Morphnarchus princeps
206        Morphnus guianensis
207       Necrosyrtes monachus
208      Neophron percnopterus
209         Nisaetus alboniger
210          Nisaetus bartelsi
211         Nisaetus cirrhatus
212            Nisaetus floris
213       Nisaetus lanceolatus
214             Nisaetus nanus
215        Nisaetus nipalensis
216      Nisaetus philippensis
217          Nisaetus pinskeri
218      Parabuteo leucorrhous
219       Parabuteo unicinctus
220            Pernis apivorus
221          Pernis celebensis
222       Pernis ptilorhynchus
223             Pernis steerei
224      Pithecophaga jefferyi
225      Polemaetus bellicosus
226      Polyboroides radiatus
227         Polyboroides typus
228      Pseudastur albicollis
229    Pseudastur occidentalis
230      Pseudastur polionotus
231      Rostrhamus sociabilis
232      Rupornis magnirostris
233           Sarcogyps calvus
234           Spilornis cheela
235           Spilornis elgini
236       Spilornis holospilus
237    Spilornis kinabaluensis
238           Spilornis klossi
239       Spilornis rufipectus
240          Spizaetus isidori
241     Spizaetus melanoleucus
242          Spizaetus ornatus
243         Spizaetus tyrannus
244    Stephanoaetus coronatus
245      Terathopius ecaudatus
246        Torgos tracheliotos
247    Trigonoceps occipitalis
248     Urotriorchis macrourus
249          Pandion haliaetus
Name: Species1, dtype: object

In [18]:



for x in testSubset: 
    species = x
    print(species)
    #species = "Accipiter badius"
    wikipedia_base = "https://en.wikipedia.org/wiki/"
    article = wikipedia_base + species
    html_doc = rq.get(article).text

    soup = bs(html_doc, 'html.parser')
    
    a = total_Para(soup)
    b = total_Words(soup)
    c = total_Ref(soup)
    
    new_row = pd.DataFrame({"SpeciesName": [species], "NumReferences": [c], "NumParagraphs": [a], "NumWords": [b]})
 
    df = pd.concat([df, new_row], ignore_index=True)
    
print(df)

Melierax poliopterus
Micronisus gabar
Milvus aegyptius
Milvus migrans
Milvus milvus
Morphnarchus princeps
Morphnus guianensis
Necrosyrtes monachus
Neophron percnopterus
Nisaetus alboniger
Nisaetus bartelsi
Nisaetus cirrhatus
Nisaetus floris
Nisaetus lanceolatus
Nisaetus nanus
Nisaetus nipalensis
Nisaetus philippensis
Nisaetus pinskeri
Parabuteo leucorrhous
Parabuteo unicinctus
Pernis apivorus
Pernis celebensis
Pernis ptilorhynchus
Pernis steerei
Pithecophaga jefferyi
Polemaetus bellicosus
Polyboroides radiatus
Polyboroides typus
Pseudastur albicollis
Pseudastur occidentalis
Pseudastur polionotus
Rostrhamus sociabilis
Rupornis magnirostris
Sarcogyps calvus
Spilornis cheela
Spilornis elgini
Spilornis holospilus
Spilornis kinabaluensis
Spilornis klossi
Spilornis rufipectus
Spizaetus isidori
Spizaetus melanoleucus
Spizaetus ornatus
Spizaetus tyrannus
Stephanoaetus coronatus
Terathopius ecaudatus
Torgos tracheliotos
Trigonoceps occipitalis
Urotriorchis macrourus
Pandion haliaetus
                SpeciesName NumReferences NumParagraphs NumWords Error
0      Melierax poliopterus             7             9     3067   NaN
1          Micronisus gabar             6             9     3331   NaN
2          Milvus aegyptius             7             8     2077   NaN
3            Milvus migrans            60            24    11001   NaN
4             Milvus milvus            76            31    17868   NaN
5     Morphnarchus princeps            10             9     4060   NaN
6       Morphnus guianensis            26            11     9701   NaN
7      Necrosyrtes monachus            27            21    10237   NaN
8     Neophron percnopterus           104            29    19999   NaN
9        Nisaetus alboniger             3             6      819   NaN
10        Nisaetus bartelsi             6             9     2576   NaN
11       Nisaetus cirrhatus            82            22    36649   NaN
12          Nisaetus floris            12             7     5198   NaN
13     Nisaetus lanceolatus             2             5      803   NaN
14           Nisaetus nanus             8             7      692   NaN
15      Nisaetus nipalensis           103            19    40016   NaN
16    Nisaetus philippensis             6            10     2358   NaN
17        Nisaetus pinskeri             9            12     3685   NaN
18    Parabuteo leucorrhous             9            12     2979   NaN
19     Parabuteo unicinctus            54            26    10323   NaN
20          Pernis apivorus            19            15     5793   NaN
21        Pernis celebensis             1             5      293   NaN
22     Pernis ptilorhynchus            23            25    12779   NaN
23           Pernis steerei             9            18     4688   NaN
24    Pithecophaga jefferyi            60            33    22153   NaN
25    Polemaetus bellicosus           201            36    72900   NaN
26    Polyboroides radiatus             4             8     2517   NaN
27       Polyboroides typus            11            10     4852   NaN
28    Pseudastur albicollis            15            15     3860   NaN
29  Pseudastur occidentalis             7            12     2801   NaN
30    Pseudastur polionotus            17            17     6261   NaN
31    Rostrhamus sociabilis            18            14     5049   NaN
32    Rupornis magnirostris            20            11     4172   NaN
33         Sarcogyps calvus            10            13     4321   NaN
34         Spilornis cheela            36            13     7658   NaN
35         Spilornis elgini            14            12     5978   NaN
36     Spilornis holospilus             3             8     1281   NaN
37  Spilornis kinabaluensis             2             3      712   NaN
38         Spilornis klossi             3             5      837   NaN
39     Spilornis rufipectus             2             4      297   NaN
40        Spizaetus isidori            25             9     9481   NaN
41   Spizaetus melanoleucus            16            16     8080   NaN
42        Spizaetus ornatus           135            61    60153   NaN
43       Spizaetus tyrannus            14             6     2796   NaN
44  Stephanoaetus coronatus           111            41    63060   NaN
45    Terathopius ecaudatus           150            37    66239   NaN
46      Torgos tracheliotos            15            20    10104   NaN
47  Trigonoceps occipitalis            14            10     6552   NaN
48   Urotriorchis macrourus             6             7     2421   NaN
49        Pandion haliaetus            78            36    16580   NaN

In [7]:
#print(soup.prettify())

species = "Dicaeum eximium"
wikipedia_base = "https://en.wikipedia.org/wiki/"
article = wikipedia_base + species
html_doc = rq.get(article).text

soup = bs(html_doc, 'html.parser')

print(total_Para(soup))
print(total_Words(soup))
print(total_Ref(soup))

5
287
1

In [3]:
print(soup.title.string) 
print(soup.find("h2", {"id": "References"})) #if it doesn't find anything, it will return none. If it does find it, it will return tag (h2) and the text 
#h2Ref = (soup.find_all("h2"))
#print(h2Ref)
#type(h2Ref)
#h2Ref.tag[id]

#looks to see if there is an h2 with the id references. If there is, do [X], and if not, do [Y]. 
#swap out whatever criteria Sandra deems sufficient evidence 
#refences is more guaranteed to exist as a header
#extract number of words in the wikipedia page, ... is that sufficient evidence??
#list of all species 
#construct a list of boolean values 
#if eveidcene exist, 
# Bird1 - True
# Bird2- False 
#Bird3 - True 

#use pandas to create a data frame 
#combining those 2 lists to create a rectangular dataset and create a csv 
# 2 variables: name, boolean value (T or F)

Shikra - Wikipedia
<h2 id="References">References</h2>

In [4]:
#everyhting we have dones so far assume wikipedia entries ... what if it does not exist
#find a weak speceis and look to see what returns 
#unique identify of no article exists 
# then put a false 
#What to do if species dne on wikipedia 

#assuming we successfully connected to wikipedia and there is no server error 

# number 1 thing to do is verfiy there is no server error!! 
# request library that talks to the server allows to figure out what type of error 
# server number is 200: which means it works 
#anything else is invalid 
# a list of server response codes 
#request if response code is 200 
#look into species 
#if response code is not 200, record a false in the boolean list 

#do a few for a test 
#what are limits to scraping wikipedia ... look up on google 
#what is the number per second, per day, per week...

In [11]:
import pandas as pd

df = pd.DataFrame(columns=["SpeciesName", "NumReferences", "NumParagraphs", "NumWords", "Error"])



birdSpecies = ["Accipiter albogularis", "Accipiter badius", "Accipiter bicolor"]

    
for i in birdSpecies:
    # Create a DataFrame for the new row
    new_row = pd.DataFrame({"SpeciesName": [i], "NumReferences": [num_references], "NumParagraphs": [totalParagraph], "NumWords": [totalWords]})
    
    # Append the new row to the existing DataFrame
    df = pd.concat([df, new_row], ignore_index=True)

# Display the DataFrame
print(df)

['Accipiter albogularis', 'Accipiter badius', 'Accipiter bicolor']
Accipiter albogularis
Accipiter badius
Accipiter bicolor
             SpeciesName NumReferences NumParagraphs NumWords Error
0  Accipiter albogularis            35            12     6188   NaN
1       Accipiter badius            35            12     6188   NaN
2      Accipiter bicolor            35            12     6188   NaN